# Generated by Django 5.2.5 on 2026-07-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
