# Generated by Django 5.2.5 on 2026-07-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_about_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonaSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image_role_label",
                    models.CharField(default="AI Automation Engineer", max_length=120),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "persona section",
                "verbose_name_plural": "persona section",
            },
        ),
        migrations.CreateModel(
            name="PhilosophyParagraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "philosophy paragraph",
                "verbose_name_plural": "philosophy paragraphs",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("skill_id", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=150)),
                ("subtitle", models.CharField(max_length=200)),
                ("proficiency", models.PositiveSmallIntegerField()),
                ("color", models.CharField(default="#a855f7", max_length=20)),
                ("icon", models.CharField(default="Bot", max_length=50)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "technical skill",
                "verbose_name_plural": "technical skills",
                "ordering": ["order", "id"],
            },
        ),
    ]
