# Generated by Django 5.2.5 on 2026-07-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_personasection_philosophyparagraph_technicalskill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("year", models.PositiveIntegerField()),
                ("short_description", models.TextField()),
                ("architectural_vision", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("icon", models.CharField(default="Activity", max_length=50)),
                ("color", models.CharField(default="#a855f7", max_length=20)),
                ("featured", models.BooleanField(default=False)),
                ("timeline", models.CharField(max_length=100)),
                ("lead_role", models.CharField(max_length=150)),
                ("environment", models.CharField(max_length=150)),
                ("goal", models.TextField()),
                ("result", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ["order", "-year", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("alt_text", models.CharField(blank=True, default="", max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project image",
                "verbose_name_plural": "project images",
                "ordering": ["order", "id"],
            },
        ),
    ]
