# Generated by Django 5.2.5 on 2026-08-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_projectimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "contact message",
                "verbose_name_plural": "contact messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EducationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("period", models.CharField(max_length=50)),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("specialization", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "education item",
                "verbose_name_plural": "education items",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeroMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("value", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                ("color", models.CharField(blank=True, default="", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "hero metric",
                "verbose_name_plural": "hero metrics",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=500)),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "social link",
                "verbose_name_plural": "social links",
                "ordering": ["order", "id"],
            },
        ),
        migrations.DeleteModel(
            name="PersonaSection",
        ),
        migrations.DeleteModel(
            name="PhilosophyParagraph",
        ),
        migrations.RemoveField(
            model_name="project",
            name="architectural_vision",
        ),
        migrations.RemoveField(
            model_name="project",
            name="color",
        ),
        migrations.RemoveField(
            model_name="project",
            name="environment",
        ),
        migrations.RemoveField(
            model_name="project",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="project",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="project",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="project",
            name="lead_role",
        ),
        migrations.RemoveField(
            model_name="project",
            name="result",
        ),
        migrations.RemoveField(
            model_name="project",
            name="timeline",
        ),
        migrations.RemoveField(
            model_name="technicalskill",
            name="color",
        ),
        migrations.RemoveField(
            model_name="technicalskill",
            name="proficiency",
        ),
        migrations.AddField(
            model_name="profile",
            name="hero_description",
            field=models.TextField(
                blank=True,
                default="Merging backend precision with agentic AI to build systems that reason, retrieve, and act.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="hero_heading",
            field=models.CharField(
                default="Engineering Agentic Intelligence", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="job_title",
            field=models.CharField(default="AI Automation Engineer", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_label",
            field=models.CharField(default="PK // REMOTE", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="resume_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="stack_label",
            field=models.CharField(default="Django • Next.js • Gemini", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="status_text",
            field=models.CharField(default="AI Automation Engineer", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="architecture",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("AI Agents", "AI Agents"),
                    ("Backend", "Backend"),
                    ("Automation", "Automation"),
                ],
                default="AI Agents",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="challenge",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="full_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="project",
            name="metrics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="pipeline_steps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="solution",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="technicalskill",
            name="details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="technicalskill",
            name="mastery",
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name="technicalskill",
            name="icon",
            field=models.CharField(default="smart_toy", max_length=50),
        ),
        migrations.AlterField(
            model_name="technicalskill",
            name="skill_id",
            field=models.CharField(max_length=50),
        ),
    ]
